version: '2'
services:
  gateway:
    image: aznu/micro-media-ordering
    ports:
      - "8090:8090"
    environment:
      MEDIA_TV_SERVER: order-tv:8080
      MEDIA_INTERNET_SERVER: order-internet:8081
      MEDIA_PAYMENT_SERVER: payment:8082
  order-tv:
    image: aznu/order-tv-service
    ports:
      - "8080:8080"
  order-internet:
    image: aznu/order-internet-service
    ports:
      - "8081:8081"
  payment:
    image: aznu/payment
    ports:
      - "8082:8082"
  media-ordering-ui:
    image: aznu/media-ordering-ui
    ports:
      - "8083:8083"
    environment:
      GATEWAY: gateway:8090